/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body - LCD Temperature Display with Design
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include <string.h>

#include "ADC_HAL.h"
#include "GPIO_HAL.h"
#include "USART_HAL.h"

uart_handle_t huart1;
uint16_t ADC_value = 0;
uint32_t temperature_C;
char temperature[64];

void delay(uint32_t ms) {
    for (volatile int i = 0; i < ms * 1000; i++);
}

void GPIO_Init_USART1(void) {
    __HAL_RCC_USART1_CLK_ENABLE();
    RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN;

    GPIOA->MODER &= ~((3 << 18) | (3 << 20));
    GPIOA->MODER |=  ((2 << 18) | (2 << 20));

    GPIOA->AFRH &= ~((0xF << 4) | (0xF << 8));
    GPIOA->AFRH |=  ((0x7 << 4) | (0x7 << 8));
}



int main(void) {
    GPIO_Init_USART1();

    huart1.Instance          = USART_1;
    huart1.Init.BaudRate     = USART_BAUD_9600;
    huart1.Init.WordLength   = USART_WL_1S8B;
    huart1.Init.StopBits     = USART_CR2_1StopBit;
    huart1.Init.OverSampling = USART_OVER16_ENABLE;
    huart1.Init.Parity       = UART_PARITY_NONE;
    huart1.Init.Mode         = (USART_REG_CR1_TE | USART_REG_CR1_RE);

    hal_uart_init(&huart1);
    NVIC_ENABLE_IRQ(USART1_IRQ_NUM);

    HAL_ADC_Init();

    while(1) {
    	HAL_ADC_Start(0);
    	HAL_ADC_WaitForConversion();

        ADC_value = HAL_ADC_Get_Value();
        temperature_C = (ADC_value * 33000) / 1023;

        uint32_t Temp_int = temperature_C / 100;
        uint32_t Temp_dec = temperature_C % 100;

        // Send via UART
        sprintf(temperature, "Temperature: %u.%02u C\r\n", (unsigned int)Temp_int, (unsigned int)Temp_dec);
        hal_uart_tx(&huart1, (uint8_t *)temperature, strlen(temperature));


        delay(1000);
    }
}

void USART1_IRQHandler(void) {
    hal_uart_handle_interrupt(&huart1);
}
